import * as readline from "readline";
import { parseProgram } from "./Parse";
import { transProgram } from "./Trans";
import { evalProgram } from "vm/Eval";

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function exit() {
    console.log("Goodbye!");
    rl.close();
    process.exit(0);
}

function toggleVerbose(oldVerbose: boolean): boolean {
    console.log(`Verbose mode is ${!oldVerbose ? "on" : "off"}`);
    return !oldVerbose;
}

export function runRepl(verbose = false) {
    rl.question("> ", (input) =>
    {
        switch (input) {
        case "exit":
            exit();
            break;
        case "verbose":
            const newVerbose = toggleVerbose(verbose);
            runRepl(newVerbose);
            break;
        default:
            try {
                // Get the parsed tree generated by ANTLR
                const parsedTree = parseProgram(input, verbose);
                // Translate the parsed tree into our own AST
                const ourTree = transProgram(parsedTree, verbose);
                // Evaluate the translated AST
                const result = evalProgram(ourTree);
                // for REPL, we always show the result
                result.show();
            } catch (err) {
                console.error('REPL: ', err);
            }
            runRepl(verbose);
        }
    });
}

