name: Node.js CI

on:
  push:
    branches:  
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
          
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Install ANTLR
      run: yarn setup-antlr

    - name: Generate ANTLR Source Files
      run: yarn lang

    - name: Install dependencies
      run: yarn install

    - name: Compile TypeScript
      run: yarn tsc

    - name: Run all tests with coverage
      run: yarn cover

    - name: Run linter
      run: yarn lint

    - name: Run prettier check
      run: yarn pretty --check

